name: "OC | P5 : Déployez un modèle de Machine Learning | Déploiement vers Hugging Face"

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Git user configuration
        run: |
          git config --global user.email "antho.lefebvre@outlook.fr"
          git config --global user.name "AnthoLFB"

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

        run: |
          git clone https://user:$HF_TOKEN@huggingface.co/spaces/AnthoLFB/deployez_un_modele_de_machine_learning space_repo

          rsync -av --exclude='.git' ./ space_repo/

          cd space_repo

          git config user.email "github-actions@example.com"
          git config user.name "github-actions"

          git add .
          git commit -m "Deploy from GitHub Actions" || echo "No changes"

          git push
