name: "OC | P5 : Déployez un modèle de Machine Learning | Déploiement vers Hugging Face"

on:
  push:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Space Destination
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "HF_SPACE=AnthoLFB/deployez_un_modele_de_machine_learning" >> $GITHUB_ENV
          else
            echo "HF_SPACE=AnthoLFB/deployez_un_modele_de_machine_learning-preprod" >> $GITHUB_ENV
          fi

      - name: Install Hugging Face CLI
        run: pip install huggingface_hub

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "Error: HF_TOKEN is not set. Check your GitHub Secrets."
            exit 1
          fi
          echo "Deploying to $HF_SPACE..."
          # Utilisation de la commande hf recommandée par les logs de la CI
          hf upload $HF_SPACE . . --repo-type=space --token=$HF_TOKEN --exclude ".git/*" ".github/*"
